from enum import Enum


class ResponseStatus(Enum):
    SUCCESS = 'SUCCESS'
    INPUT_ERROR = 'INPUT_ERROR'
    NO_FACE_ERROR = 'NO_FACE_ERROR'
    ERROR = 'ERROR'
    PEOPLE_NOT_FOUND_ERROR = 'PEOPLE_NOT_FOUND_ERROR'
    LIVENESS_FAIL = 'LIVENESS_FAIL'
    PEOPLE_DO_NOT_EXITS_ERROR = 'PEOPLE_DO_NOT_EXITS_ERROR'

