version: '3.1'

services:

  db:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ./data_file/:/var/lib/mysql/
      - ./conf/:/etc/mysql/conf.d/